repository: SupratimManna/portfolio
version: 2

# Personal info
name: Supratim Manna
title: Data Scientist | AI/ML Researcher
email: supratimmannas7@gmail.com
phone: +91 6294034588
website: https://github.com/Supratimmannas7

darkmode: false

github_username: Supratimmannas7
linkedin_username: supratim-manna-728315293
kaggle_username: supratimmanna7
youtube_username: SupratimManna

about_profile_image: images/profile.jpg
about_content: |
  Passionate Data Science student at DIAT-DRDO, exploring AI/ML research with a focus on **Generative AI**, **Diffusion Models**, and **GANs**. Enthusiastic about solving real-world problems using data-driven approaches.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: Exoplanet Detection using ML
        link: https://github.com/Supratimmannas7/Exoplanet-Detection
        link_text: GitHub Repository
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/Supratimmannas7/Exoplanet-Detection
        quote: "Using k-NN for identifying exoplanets from light intensity data."
        description: |
          Developed an ML-based approach to detect exoplanets using **k-NN** on light curves, enhancing classification accuracy in astronomical research.
      
      - layout: left
        border: weak
        title: CyberAICup 2024 - Network IDS
        link: https://github.com/Supratimmannas7/CyberAICup2024
        link_text: GitHub Repository
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/Supratimmannas7/CyberAICup2024
        quote: "AI-driven Intrusion Detection using LightGBM."
        description: |
          Built a **Network Intrusion Detection System** (NIDS) using **LightGBM**, enhancing security with real-time monitoring.
  
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Innovate Intern - AI/ML
        sub_title: AICTE Virtual Internship
        caption: July 2024 - November 2024
        quote: "Exploring AI applications through real-world projects."
        description: |
          Worked on **Deep Learning and NLP** projects, gaining hands-on experience in **Transformer models, GANs, and AI ethics**.
  
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Defence Institute of Advanced Technology (DIAT-DRDO)
        sub_title: M.Sc. Data Science (Applied Mathematics)
        caption: 2023 - 2025
        description: |
          Focused on **Machine Learning, Deep Learning, and Generative AI**, with research on **AIS anomaly detection** and **fNIRS-based Brain-Computer Interfaces**.
  
  - title: Skills
    layout: text
    content: |
      **Programming:** Python, SQL, R  
      **ML/DL Frameworks:** TensorFlow, PyTorch, Scikit-learn  
      **Data Science:** Pandas, NumPy, Seaborn, Matplotlib  
      **AI Techniques:** CNN, LSTM, GANs, Transformers, Diffusion Models  
      **Mathematical Background:** Linear Algebra, Probability, Graph Theory  

footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/"]
